### PR TITLE
Remove devise secret key

### PR DESCRIPTION
**Pull request by tmaier**
Stuff like this should not be in github...

And please open the issue tracker on GitHub or provide a link to a live demo of yours.

### CODE REVIEW

**Comment by ghost** [comment]
Hey this is a fork (although it doesn't say it is). Head over to the original [repo here](https://github.com/rafalchmiel/issuet).

**Comment by tmaier** [comment]
Thank you! Didn't know about the project.

**Comment by ghost** [comment]
Also, I doubt I'll be continuing working on the project so you might just want to fork it and play around with it on your own. Thanks for your interest otherwise!

I just pushed a quick demo to [still-cliffs-9245.herokuapp.com](http://still-cliffs-9245.herokuapp.com/).

**Comment by tmaier** [comment]
What's your reasoning behind this?

**Comment by ghost** [comment]
Just got some other stuff I'm working on at the moment. Of course, if you have any questions just ping me on the issue tracker on GitHub.

**Pull request merged**
